# Generated by Django 5.2.12 on 2026-03-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='指標代碼')),
                ('name', models.CharField(max_length=200, verbose_name='指標名稱')),
                ('category', models.CharField(choices=[('整體照護', '整體照護'), ('加護照護', '加護照護'), ('手術照護', '手術照護'), ('產科照護', '產科照護'), ('急診照護', '急診照護'), ('重點照護', '重點照護'), ('感染管制', '感染管制'), ('用藥安全', '用藥安全'), ('呼吸照護', '呼吸照護'), ('經營管理', '經營管理')], max_length=20, verbose_name='類別')),
                ('unit', models.CharField(choices=[('percent', '百分比 (%)'), ('permille', '千分比 (‰)'), ('count', '件數'), ('ratio', '比值')], max_length=20, verbose_name='單位')),
                ('direction', models.CharField(choices=[('lower', '越低越好'), ('higher', '越高越好'), ('monitor', '監測')], max_length=10, verbose_name='方向')),
                ('data_nature', models.CharField(choices=[('continuous', '連續型（計數）'), ('binomial_rate', '二項比率'), ('poisson_rate', 'Poisson 密度')], default='continuous', max_length=20, verbose_name='資料性質')),
                ('is_quarterly', models.BooleanField(default=False, verbose_name='季指標')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('source', models.CharField(choices=[('preset', '預設'), ('custom', '自訂')], default='preset', max_length=10, verbose_name='來源')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='別名列表')),
                ('campuses', models.JSONField(default=list, verbose_name='適用院區')),
                ('formula', models.TextField(blank=True, default='', verbose_name='計算公式')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '指標',
                'verbose_name_plural': '指標',
                'db_table': 'indicators',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（區域醫院）'), ('竹東', '竹東（地區醫院）'), ('新竹', '新竹（醫學中心）')], max_length=10, verbose_name='院區')),
                ('year', models.IntegerField(verbose_name='年度（民國年）')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='值')),
                ('numerator', models.IntegerField(blank=True, null=True, verbose_name='分子')),
                ('denominator', models.IntegerField(blank=True, null=True, verbose_name='分母')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('import_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.importlog')),
                ('indicator', models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='indicators.indicator', to_field='code')),
            ],
            options={
                'verbose_name': '資料點',
                'verbose_name_plural': '資料點',
                'db_table': 'data_points',
                'indexes': [models.Index(fields=['indicator', 'campus', 'year'], name='data_points_indicat_d4c6af_idx')],
                'unique_together': {('indicator', 'campus', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（區域醫院）'), ('竹東', '竹東（地區醫院）'), ('新竹', '新竹（醫學中心）')], max_length=10, verbose_name='院區')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('mechanism', models.CharField(choices=[('control_chart', '管制圖'), ('monthly_change', '月增減'), ('peer_comparison', '同儕比較')], max_length=20, verbose_name='偵測機制')),
                ('rule', models.CharField(blank=True, default='', max_length=50, verbose_name='規則')),
                ('severity', models.CharField(choices=[('excellent', '卓越'), ('good', '良好'), ('watch', '留意'), ('warning', '注意'), ('alert', '警示'), ('neutral', '監測中')], max_length=10, verbose_name='嚴重度')),
                ('message', models.CharField(max_length=500, verbose_name='訊息')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='已確認')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('indicator', models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='indicators.indicator', to_field='code')),
            ],
            options={
                'verbose_name': '異常警示',
                'verbose_name_plural': '異常警示',
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['indicator', 'campus', 'year', 'month'], name='alerts_indicat_2a8ed0_idx'), models.Index(fields=['severity'], name='alerts_severit_362484_idx'), models.Index(fields=['acknowledged'], name='alerts_acknowl_046d76_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（區域醫院）'), ('竹東', '竹東（地區醫院）'), ('新竹', '新竹（醫學中心）')], max_length=10, verbose_name='院區')),
                ('value', models.FloatField(verbose_name='同儕值')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('indicator', models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, related_name='peer_values', to='indicators.indicator', to_field='code')),
            ],
            options={
                'verbose_name': '同儕值',
                'verbose_name_plural': '同儕值',
                'db_table': 'peer_values',
                'unique_together': {('indicator', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='TCPIBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcpi_name', models.CharField(max_length=200, verbose_name='TCPI 指標名稱')),
                ('year', models.IntegerField(verbose_name='TCPI 年度（民國年）')),
                ('medical_center', models.FloatField(blank=True, null=True, verbose_name='醫學中心同儕值')),
                ('regional_hospital', models.FloatField(blank=True, null=True, verbose_name='區域醫院同儕值')),
                ('district_hospital', models.FloatField(blank=True, null=True, verbose_name='地區醫院同儕值')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='匯入時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('indicator', models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, related_name='tcpi_benchmarks', to='indicators.indicator', to_field='code')),
            ],
            options={
                'verbose_name': 'TCPI 標竿',
                'verbose_name_plural': 'TCPI 標竿',
                'db_table': 'tcpi_benchmarks',
                'indexes': [models.Index(fields=['indicator', 'year'], name='tcpi_benchm_indicat_d879b8_idx')],
                'unique_together': {('indicator', 'year')},
            },
        ),
        migrations.CreateModel(
            name='YearlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（區域醫院）'), ('竹東', '竹東（地區醫院）'), ('新竹', '新竹（醫學中心）')], max_length=10, verbose_name='院區')),
                ('year', models.IntegerField(verbose_name='年度（民國年）')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='年平均值')),
                ('benchmark_regional', models.FloatField(blank=True, null=True, verbose_name='區域醫院標竿')),
                ('benchmark_district', models.FloatField(blank=True, null=True, verbose_name='地區醫院標竿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('import_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.importlog')),
                ('indicator', models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, related_name='yearly_summaries', to='indicators.indicator', to_field='code')),
            ],
            options={
                'verbose_name': '年度彙總',
                'verbose_name_plural': '年度彙總',
                'db_table': 'yearly_summaries',
                'unique_together': {('indicator', 'campus', 'year')},
            },
        ),
    ]
