# Generated by Django 6.0.3 on 2026-05-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_datapoint_nd_to_float'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datapointsubcategory',
            new_name='data_point__parent__a35523_idx',
            old_name='data_point__parent__52d5e3_idx',
        ),
        migrations.AlterField(
            model_name='datapointsubcategory',
            name='campus',
            field=models.CharField(choices=[('竹北', '竹北（區域醫院）'), ('竹東', '竹東（地區醫院）'), ('新竹', '新竹（醫學中心）')], max_length=10, verbose_name='院區'),
        ),
        migrations.AlterField(
            model_name='datapointsubcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
