# Generated by Django 6.0.3 on 2026-07-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DavinciImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_file', models.FileField(blank=True, upload_to='davinci_imports/%Y/%m/')),
                ('status', models.CharField(choices=[('preview', '預覽中'), ('confirmed', '已確認寫入'), ('discarded', '已捨棄')], default='preview', max_length=20)),
                ('periods', models.JSONField(default=list)),
                ('campuses', models.JSONField(default=list)),
                ('rows_raw', models.IntegerField(default=0)),
                ('cases_dedup', models.IntegerField(default=0)),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'davinci_import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DavinciCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（生醫醫院）'), ('新竹', '新竹醫院')], max_length=10)),
                ('period', models.IntegerField()),
                ('account', models.CharField(max_length=20)),
                ('chart_no_masked', models.CharField(blank=True, max_length=20)),
                ('patient_masked', models.CharField(blank=True, max_length=20)),
                ('davinci_type', models.CharField(blank=True, max_length=10)),
                ('dept_code', models.CharField(blank=True, max_length=10)),
                ('dept_name', models.CharField(blank=True, max_length=50)),
                ('surgeon', models.CharField(blank=True, max_length=50)),
                ('order_codes', models.JSONField(default=list)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('op_date', models.DateField(blank=True, null=True)),
                ('op_date_raw', models.CharField(blank=True, max_length=40)),
                ('op_time_min', models.FloatField(blank=True, null=True)),
                ('blood_ml', models.FloatField(blank=True, null=True)),
                ('conversion', models.BooleanField(default=False)),
                ('conversion_reason', models.CharField(blank=True, max_length=200)),
                ('adverse_14d', models.BooleanField(default=False)),
                ('adverse_codes', models.JSONField(default=list)),
                ('adverse_free_text', models.CharField(blank=True, max_length=200)),
                ('severe_comp_30d', models.BooleanField(default=False)),
                ('severe_comp_codes', models.JSONField(default=list)),
                ('infection_14d', models.BooleanField(default=False)),
                ('reoperation_14d', models.BooleanField(default=False)),
                ('flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='davinci.davinciimportlog')),
            ],
            options={
                'db_table': 'davinci_cases',
                'ordering': ['campus', 'period', 'account'],
                'indexes': [models.Index(fields=['campus', 'period'], name='davinci_cas_campus_a9ca1f_idx'), models.Index(fields=['campus', 'period', 'dept_code'], name='davinci_cas_campus_023936_idx'), models.Index(fields=['campus', 'period', 'surgeon'], name='davinci_cas_campus_2c4e90_idx')],
                'unique_together': {('campus', 'period', 'account')},
            },
        ),
        migrations.CreateModel(
            name='DavinciIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('竹北', '竹北（生醫醫院）'), ('新竹', '新竹醫院')], max_length=10)),
                ('period', models.IntegerField()),
                ('indicator_code', models.CharField(max_length=10)),
                ('numerator', models.IntegerField(blank=True, null=True)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('median_value', models.FloatField(blank=True, null=True)),
                ('n_cases', models.IntegerField(default=0)),
                ('n_excluded', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_values', to='davinci.davinciimportlog')),
            ],
            options={
                'db_table': 'davinci_indicator_values',
                'ordering': ['campus', 'period', 'indicator_code'],
                'indexes': [models.Index(fields=['campus', 'indicator_code', 'period'], name='davinci_ind_campus_fd2403_idx')],
                'unique_together': {('campus', 'period', 'indicator_code')},
            },
        ),
    ]
