# Generated by Django 5.2.12 on 2026-03-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name'], 'verbose_name': '院區', 'verbose_name_plural': '院區'},
        ),
        migrations.AlterModelOptions(
            name='caserecord',
            options={'verbose_name': '個案紀錄', 'verbose_name_plural': '個案紀錄'},
        ),
        migrations.AlterModelOptions(
            name='datasourceconfig',
            options={'verbose_name': '資料來源設定', 'verbose_name_plural': '資料來源設定'},
        ),
        migrations.AlterModelOptions(
            name='deadlinesetting',
            options={'verbose_name': '截止日設定', 'verbose_name_plural': '截止日設定'},
        ),
        migrations.AlterModelOptions(
            name='entryauditlog',
            options={'ordering': ['-changed_at'], 'verbose_name': '修改紀錄', 'verbose_name_plural': '修改紀錄'},
        ),
        migrations.AlterModelOptions(
            name='exclusionreason',
            options={'ordering': ['sort_order'], 'verbose_name': '排除理由', 'verbose_name_plural': '排除理由'},
        ),
        migrations.AlterModelOptions(
            name='ha10subentry',
            options={'verbose_name': 'HA10 子類別', 'verbose_name_plural': 'HA10 子類別'},
        ),
        migrations.AlterModelOptions(
            name='hisfieldmapping',
            options={'verbose_name': 'HIS 欄位對應', 'verbose_name_plural': 'HIS 欄位對應'},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-imported_at'], 'verbose_name': '匯入批次', 'verbose_name_plural': '匯入批次'},
        ),
        migrations.AlterModelOptions(
            name='indicatorassignment',
            options={'verbose_name': '指標負責人指派', 'verbose_name_plural': '指標負責人指派'},
        ),
        migrations.AlterModelOptions(
            name='indicatorentry',
            options={'verbose_name': '指標數據', 'verbose_name_plural': '指標數據'},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'verbose_name': '月報', 'verbose_name_plural': '月報'},
        ),
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'ordering': ['sort_order'], 'verbose_name': '填報面向', 'verbose_name_plural': '填報面向'},
        ),
        migrations.RenameIndex(
            model_name='caserecord',
            new_name='entry_case__entry_i_36d960_idx',
            old_name='entry_case_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatorassignment',
            new_name='entry_assig_indicat_0a57c3_idx',
            old_name='entry_assig_indicat_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='entry_month_campus__d7761f_idx',
            old_name='entry_month_campus_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='entry_month_status_15797b_idx',
            old_name='entry_month_status_idx',
        ),
    ]
