# Generated by Django 5.2.12 on 2026-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('file_size', models.IntegerField(verbose_name='檔案大小 (bytes)')),
                ('sheets_processed', models.JSONField(default=list, verbose_name='處理的工作表')),
                ('data_points_new', models.IntegerField(default=0, verbose_name='新增資料點')),
                ('data_points_updated', models.IntegerField(default=0, verbose_name='更新資料點')),
                ('data_points_unchanged', models.IntegerField(default=0, verbose_name='未變更資料點')),
                ('revisions_detected', models.IntegerField(default=0, verbose_name='偵測到的修訂')),
                ('errors', models.JSONField(default=list, verbose_name='錯誤訊息')),
                ('uploaded_file', models.FileField(blank=True, upload_to='imports/%Y/%m/', verbose_name='上傳檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '匯入紀錄',
                'verbose_name_plural': '匯入紀錄',
                'db_table': 'import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_name', models.CharField(max_length=200, verbose_name='Excel 名稱')),
                ('normalized_name', models.CharField(db_index=True, max_length=200, verbose_name='標準化名稱')),
                ('indicator_code', models.CharField(db_index=True, max_length=20, verbose_name='指標代碼')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='確認時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '比對規則',
                'verbose_name_plural': '比對規則',
                'db_table': 'matching_rules',
            },
        ),
    ]
